name: Build libmpv-android

on: 
  push:
    branches:
      - main
  pull_request:

env:
  NDK_VER: 25.2.9519653

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Gradle Build Action
        uses: gradle/gradle-build-action@v2
      - name: Cache
        uses: actions/cache@v3
        with:
          path: /usr/local/lib/android/sdk/ndk/${{ env.NDK_VER }}
          key: ${{ runner.os }}-${{ env.NDK_VER }}
      - name: Symlink SDK
        working-directory: ./buildscripts
        run: |
          mkdir sdk
          ln -s ${ANDROID_HOME} ./sdk/android-sdk-linux
      - name: Download dependencies
        working-directory: ./buildscripts
        run: ./download.sh
      - name: Apply patches
        working-directory: ./buildscripts
        run: ./patch.sh
      - name: Build
        working-directory: ./buildscripts
        run: ./build.sh
      - uses: actions/upload-artifact@v3
        with:
          name: libmpv-release.aar
          path: ./libmpv/build/outputs/aar/libmpv-release.aar
